name: testing

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'
    - 
      name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - 
      name: test
      run: go test -v ./...
